
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 15 18:46:45 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 37;
  public static final int LTE = 33;
  public static final int LBRACKET = 46;
  public static final int CHAR = 59;
  public static final int CONST = 8;
  public static final int HASH = 53;
  public static final int LPAREN = 42;
  public static final int SEMI = 4;
  public static final int CONTINUE = 18;
  public static final int MINUS = 24;
  public static final int RPAREN = 43;
  public static final int AND = 34;
  public static final int LT = 32;
  public static final int RECORD = 22;
  public static final int OR = 35;
  public static final int BOOL = 60;
  public static final int CLASS = 5;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 9;
  public static final int CARET = 49;
  public static final int THIS = 19;
  public static final int FACT = 50;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 38;
  public static final int RETURN = 15;
  public static final int RBRACKET = 47;
  public static final int EQUAL = 36;
  public static final int SUPER = 20;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int MUL = 25;
  public static final int PERCENT = 27;
  public static final int NUMBER = 58;
  public static final int ET = 54;
  public static final int NEQ = 29;
  public static final int IDENT = 57;
  public static final int BREAK = 3;
  public static final int VOID = 16;
  public static final int EQ = 28;
  public static final int GTE = 31;
  public static final int COLON = 39;
  public static final int LBRACE = 44;
  public static final int ELSE = 7;
  public static final int SKIP = 56;
  public static final int ENUM = 6;
  public static final int READ = 14;
  public static final int GOTO = 21;
  public static final int FINAL = 55;
  public static final int WHILE = 11;
  public static final int RBRACE = 45;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int QUESTION = 48;
  public static final int MAX = 52;
  public static final int SWAP = 51;
  public static final int GT = 30;
  public static final int PRINT = 13;
  public static final int DO = 10;
}

